import { LineEdit, VerticalBox, StandardListView } from "std-widgets.slint";

struct slint_NetDevice {
    ip_addr: string,
    mac_addr: string,
    manufacturer: string,
}

export component AppWindow inherits Window {
    title: "NETEYE";
    width: 800px;
    height: 600px;

    callback scan_ports(string);
    in-out property <[slint_NetDevice]> devices;
    in-out property <bool> is_scanning: false;

    Rectangle {
        background: @linear-gradient(180deg, #f1f1f1 0%, #f0f0f0 100%);
    }

    VerticalLayout {
        padding: 20px;
        spacing: 10px;
        alignment: stretch;

        Text {
            text: "NETWORK:";
            font-size: 16px;
        }

        HorizontalLayout {
            spacing: 10px;

            net_addr_input := LineEdit {
                placeholder-text: "e.g., 192.168.0.0/24";
                text: "192.168.0.0/24";
            }

            btn_scan := Rectangle {
                background: btn_scan_touch.pressed ? #007ade : #008cff;
                height: 40px;
                width: 100px;
                border-radius: 4px;
                opacity: is_scanning ? 0.6 : 1;

                btn_scan_touch := TouchArea {
                    enabled: !is_scanning;
                    mouse-cursor: is_scanning ? default : pointer;

                    Text {
                        text: is_scanning ? "WAIT" : "SCAN";
                        color: white;
                        font-weight: 800;
                    }

                    clicked => {
                        root.scan_ports(net_addr_input.text);
                    }
                }
            }
        }

        VerticalBox {
            StandardListView {
                width: 100%;
                height: 100%;

                for dev[index] in devices: Rectangle {
                    height: 100px;
                    background: mod(index, 2) == 0 ? #ffffff : #f5f5f5;

                    HorizontalLayout {
                        alignment: start;
                        padding: 10px;

                        VerticalLayout {
                            Text {
                                text: dev.ip_addr;
                                font-size: 20px;
                            }

                            Text {
                                text: "MAC: \{dev.mac_addr}";
                                font-size: 15px;
                                color: gray;
                            }

                            Text {
                                text: "MAN: \{dev.manufacturer}";
                                font-size: 15px;
                                color: gray;
                            }
                        }
                    }
                }
            }
        }
    }
}
