import { LineEdit, Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "NETEYE";
    width: 800px;
    height: 600px;

    callback scan_ports(string);
    in-out property <string> scan_results: "Scan results will appear here...";

    Rectangle {
        background: @linear-gradient(180deg, #000d1a 0%, #002d5a 100%);
    }

    VerticalLayout {
        padding: 20px;
        spacing: 10px;
        alignment: stretch;

        Text {
            text: "NETWORK:";
            color: white;
            font-size: 16px;
        }

        HorizontalLayout {
            spacing: 10px;

            net_addr_input := LineEdit {
                placeholder-text: "e.g., 192.168.0.0/24";
                text: "192.168.0.0/24";
            }

            btn_scan := Rectangle {
                background: #008cff;
                height: 40px;
                width: 100px;
                border-radius: 4px;

                TouchArea {
                    mouse-cursor: pointer;

                    Text {
                        text: "SCAN";
                        color: white;
                        font-weight: 800;
                    }

                    clicked => {
                        root.scan_ports(net_addr_input.text);
                    }
                }
            }
        }

        Rectangle {
            background: #002d5a;

            Text {
                x: 8px;
                y: 8px;
                text: scan_results;
                color: white;
                vertical-stretch: 1;
            }
        }
    }
}
