export component MainView {
    width: 800px;
    height: 500px;
    
    Text {
        font-family: "";
        font-italic: false;
        font-size: 20px;
        font-weight: 900;
        text: "NETWORK:";
        x: 220px;
        y: 236px;
    }
    
    TextInput {
        font-size: 20px;
        height: 28px;
        input-type: InputType.text;
        text: "192.168.0.0/24";
        x: 340px;
        y: 236px;
        width: 251px;
    }
}
